name: Integration Test

on: [push, pull_request]

jobs:
  integration-pre-212:
    name: Integ-pre-212
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        opensearch_version: [ '1.0.1', '1.3.7' ]
        secured: [ "true", "false" ]
    env:
      OPENSEARCH_VERSION: ${{ matrix.opensearch_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Integ OpenSearch secured=${{ matrix.secured }} version=${{ matrix.opensearch_version }}
        run: "./.ci/run-tests ${{ matrix.secured }} ${{ matrix.opensearch_version }}"

  integration-post-212:
    name: Integ-post-212
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        opensearch_version: [ '2.14.0', '2.16.0' ]
        secured: [ "true", "false" ]
    env:
      OPENSEARCH_URL: 'https://admin:myStrongPassword123!@localhost:9200'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'myStrongPassword123!'
      OPENSEARCH_VERSION: ${{ matrix.opensearch_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Integ OpenSearch secured=${{ matrix.secured }} version=${{ matrix.opensearch_version }}
        run: "./.ci/run-tests ${{ matrix.secured }} ${{ matrix.opensearch_version }}"
